app:
   name: airbus
   description: airbus Application

spring:
  mvc:
    view:
      prefix: /WEB-INF/static/
      suffix: .html
  profiles:
    active: test

---
spring:
    profiles: dev

server:
   port: 8080

jdbc:
     url: jdbc:mysql://10.255.132.19:3306/testdb
     username: testdb
     password: testdb

---

spring:
    profiles: test

server:
   port: 80

jdbc:
     url: jdbc:mysql://10.255.4.26:3306/test
     username: sims
     password: simsconsult
---

spring:
    profiles: prod

server:
   port: 80

shell.auth.simple.user:
    name: peter
    password: 119