app:
   name: airbus
   description: airbus Application

spring:
  mvc:
    view:
      prefix: /WEB-INF/static/
      suffix: .html
  profiles:
    active: test

---
spring:
    profiles: dev

server:
   port: 8080

---

spring:
    profiles: test

server:
   port: 80

---

spring:
    profiles: prod

server:
   port: 80

shell.auth.simple.user:
    name: peter
    password: 119